name: Deployment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build_and_upload_macos_binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Build
        run: shards build --production --release --no-debug
      - name: Check version matches tag
        run: "[[ \"v$(./skedjewel --version)\" == ${{ github.event.release.tag_name }} ]] || exit 1"
      - name: Rename
        run: mv skedjewel skedjewel-${{ github.event.release.tag_name }}-darwin
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: skedjewel-${{ github.event.release.tag_name }}-darwin
